//! M0 validation: the 2-turn square spiral fixture against independent
//! references.
//!
//! # Fixture
//!
//! The same fixture klayout-tools validates its MoM PEEC against
//! (`docs/design/mom-validation.md` §5): a 2-turn square spiral, starting
//! side 60 µm, 15 µm pitch growth per turn (segment lengths 60, 60, 75, 75,
//! 90, 90, 105, 105 µm), 2×2 µm copper cross-section — built by the
//! standard non-self-intersecting construction. The port closes the spiral
//! from its end back to its start, so `Im Z(ω)/ω` is the spiral's total
//! inductance with all mutual coupling included, and `Re Z(0)` its DC
//! resistance.
//!
//! # References
//!
//! 1. **Greenhouse segment summation** (computed in this file, sharing no
//!    code with the production kernels): Rosa/Greenhouse self terms plus
//!    the exact parallel-filament mutual (the double integral has the
//!    closed form `I(u) = u·asinh(u/d) − √(u²+d²)` evaluated at the four
//!    endpoint differences), signed by relative winding direction and zero
//!    for perpendicular segments. Stated tolerance 5 %.
//! 2. **PyPEEC** (MPL-2.0 voxel quasi-magnetostatic solver): a fully
//!    independent discretization and solve, regenerated by
//!    `tools/pypeec_reference.py` (1 µm voxels, DC + 1 kHz) and read from
//!    the JSON that script writes. Stated tolerance 2 %. The test skips
//!    with an explicit reason when the reference file is absent; the CI
//!    "validation" step regenerates it first and asserts the test did not
//!    skip.
//! 3. **Mohan modified-Wheeler** (computed here, reported, not asserted):
//!    the current-sheet expression `L = K₁µ₀n²d_avg/(1+K₂ρ)` with the
//!    square-spiral constants `K₁ = 2.34`, `K₂ = 2.75` — a ±20 %-class
//!    estimate for a spiral this small, included for the record.

use fasterhenry::geometry::{Geometry, Node, NodeId, SegmentDef};
use fasterhenry::mesh::Port;
use fasterhenry::solve::{solve, Discretization, Subdivision};
use fasterhenry::SweepResult;
use std::path::PathBuf;

const UM: f64 = 1e-6;
const SIGMA: f64 = 5.8e7;
const W_UM: f64 = 2.0;
const T_UM: f64 = 2.0;
const FREQ_HZ: f64 = 1.0e3; // skin depth 66 µm >> 2 µm: uniform current

type Segment = ((f64, f64), (f64, f64)); // centreline endpoints, µm

/// The standard non-self-intersecting square spiral (winding order).
fn square_spiral_segments(turns: usize, start_len_um: f64, pitch_um: f64) -> Vec<Segment> {
    let directions = [(1.0, 0.0), (0.0, 1.0), (-1.0, 0.0), (0.0, -1.0)];
    let mut position = (0.0, 0.0);
    let mut length = start_len_um;
    let mut segments = Vec::new();
    for k in 0..turns * 4 {
        let direction = directions[k % 4];
        let end = (
            position.0 + direction.0 * length,
            position.1 + direction.1 * length,
        );
        segments.push((position, end));
        position = end;
        if k % 2 == 1 {
            length += pitch_um;
        }
    }
    segments
}

/// The fixture as a solvable geometry: 8 segments head-to-tail around 9
/// shared vertices, the port closing the spiral from end back to start.
fn spiral_system() -> (Geometry, Vec<Port>, Discretization) {
    let segments = square_spiral_segments(2, 60.0, 15.0);
    let mut nodes = Vec::new();
    nodes.push(Node::new(0.0, 0.0, T_UM / 2.0 * UM));
    for &(.., end) in &segments {
        nodes.push(Node::new(end.0 * UM, end.1 * UM, T_UM / 2.0 * UM));
    }
    let defs: Vec<SegmentDef> = (0..segments.len())
        .map(|i| {
            SegmentDef::new(
                NodeId(i),
                NodeId(i + 1),
                W_UM * UM,
                T_UM * UM,
                SIGMA,
            )
        })
        .collect();
    let geometry = Geometry::from_parts(nodes, defs).unwrap();
    let ports = vec![Port::new(NodeId(0), NodeId(segments.len())).named("spiral")];
    let discretization = Discretization::PerSegment(vec![Subdivision::new(4, 4); segments.len()]);
    (geometry, ports, discretization)
}

/// fasterhenry's total spiral inductance at `FREQ_HZ` and DC resistance.
fn extract() -> (f64, f64, SweepResult) {
    let (geometry, ports, discretization) = spiral_system();
    let result = solve(&geometry, &ports, &discretization, &[0.0, FREQ_HZ]).unwrap();
    let z = &result.impedance_ohm[1][(0, 0)];
    let inductance = z.im / (std::f64::consts::TAU * FREQ_HZ);
    let resistance = result.impedance_ohm[0][(0, 0)].re;
    (inductance, resistance, result)
}

// --- Greenhouse segment summation (independent of the production kernels) ---

/// Rosa/Greenhouse self term of a rectangular-conductor segment (metres).
fn greenhouse_self(length_um: f64, w_um: f64, t_um: f64) -> f64 {
    let (l, g) = (length_um * UM, (w_um + t_um) * UM);
    const MU0: f64 = 2.0 * std::f64::consts::TAU * 1e-7;
    MU0 / std::f64::consts::TAU * l * ((2.0 * l / g).ln() + 0.50049 + g / (3.0 * l))
}

/// Exact mutual of two parallel filaments: the closed form of the double
/// integral of 1/R over both lengths, lateral distance `d` (all metres),
/// evaluated at the four endpoint differences.
fn filament_mutual(s0: f64, s1: f64, t0: f64, t1: f64, d: f64) -> f64 {
    const MU0: f64 = 2.0 * std::f64::consts::TAU * 1e-7;
    let i = |u: f64| (u / d).asinh() * u - (u * u + d * d).sqrt();
    MU0 / (std::f64::consts::TAU * 2.0) * (i(s1 - t0) - i(s1 - t1) - i(s0 - t0) + i(s0 - t1))
}

/// Greenhouse total for the spiral: self terms plus orientation-signed
/// parallel mutuals (perpendicular segments do not couple).
fn greenhouse_total(segments: &[Segment]) -> f64 {
    let mut total = 0.0;
    for &(start, end) in segments {
        let length = (end.0 - start.0).abs().max((end.1 - start.1).abs());
        total += greenhouse_self(length, W_UM, T_UM);
    }
    for (i, &(a_start, a_end)) in segments.iter().enumerate() {
        for &(b_start, b_end) in segments.iter().skip(i + 1) {
            let a_horizontal = (a_end.0 - a_start.0).abs() > (a_end.1 - a_start.1).abs();
            let b_horizontal = (b_end.0 - b_start.0).abs() > (b_end.1 - b_start.1).abs();
            if a_horizontal != b_horizontal {
                continue; // perpendicular: zero mutual
            }
            let (d, a, b, same_direction) = if a_horizontal {
                (
                    (a_start.1 - b_start.1).abs() * UM,
                    (a_start.0, a_end.0),
                    (b_start.0, b_end.0),
                    (a_end.0 - a_start.0) * (b_end.0 - b_start.0) > 0.0,
                )
            } else {
                (
                    (a_start.0 - b_start.0).abs() * UM,
                    (a_start.1, a_end.1),
                    (b_start.1, b_end.1),
                    (a_end.1 - a_start.1) * (b_end.1 - b_start.1) > 0.0,
                )
            };
            let sign = if same_direction { 1.0 } else { -1.0 };
            // Sort the axis coordinates so the closed form sees positive
            // bounds; the relative-direction sign carries the orientation.
            let (s0, s1) = if a.0 <= a.1 { (a.0, a.1) } else { (a.1, a.0) };
            let (t0, t1) = if b.0 <= b.1 { (b.0, b.1) } else { (b.1, b.0) };
            total += 2.0
                * sign
                * filament_mutual(s0 * UM, s1 * UM, t0 * UM, t1 * UM, d);
        }
    }
    total
}

/// Mohan modified-Wheeler square-spirar estimate (reported, not asserted).
fn mohan_modified_wheeler(segments: &[Segment]) -> f64 {
    let mut lo = (f64::INFINITY, f64::INFINITY);
    let mut hi = (f64::NEG_INFINITY, f64::NEG_INFINITY);
    for &(start, end) in segments {
        for (x, y) in [(start.0, start.1), (end.0, end.1)] {
            lo.0 = lo.0.min(x - W_UM / 2.0);
            lo.1 = lo.1.min(y - W_UM / 2.0);
            hi.0 = hi.0.max(x + W_UM / 2.0);
            hi.1 = hi.1.max(y + W_UM / 2.0);
        }
    }
    let d_out = ((hi.0 - lo.0).max(hi.1 - lo.1)) * UM;
    // Inner hollow: bounded by the first turn's centrelines, minus the metal.
    let d_in = (60.0 - 2.0 * W_UM) * UM;
    let n = 2.0_f64;
    let (k1, k2) = (2.34, 2.75);
    let d_avg = (d_out + d_in) / 2.0;
    let fill = (d_out - d_in) / (d_out + d_in);
    const MU0: f64 = 2.0 * std::f64::consts::TAU * 1e-7;
    k1 * MU0 * n * n * d_avg / (1.0 + k2 * fill)
}

/// The PyPEEC reference JSON, if it was generated.
fn pypeec_reference() -> Option<PathBuf> {
    let path = std::env::var("FASTERHENRY_PYPEEC_REFERENCE")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../tools/pypeec_reference.json")
        });
    path.exists().then_some(path)
}

#[test]
fn spiral_inductance_against_references() {
    let segments = square_spiral_segments(2, 60.0, 15.0);
    let (inductance, resistance, result) = extract();

    let greenhouse = greenhouse_total(&segments);
    let mohan = mohan_modified_wheeler(&segments);
    let dc_analytic = segments
        .iter()
        .map(|&(start, end)| {
            ((end.0 - start.0).abs().max((end.1 - start.1).abs()) * UM)
                / (SIGMA * W_UM * UM * T_UM * UM)
        })
        .sum::<f64>();

    println!("fasterhenry  L = {:.6} nH   R = {:.6} ohm", inductance * 1e9, resistance);
    println!("greenhouse  L = {:.6} nH", greenhouse * 1e9);
    println!("mohan-mw    L = {:.6} nH (reported, ±20 % class)", mohan * 1e9);
    println!("dc analytic R = {:.6} ohm", dc_analytic);

    // DC resistance: exact series sum, no proximity correction at DC.
    assert!(
        (resistance - dc_analytic).abs() / dc_analytic < 5e-3,
        "fasterhenry DC resistance {resistance:.6} vs analytic {dc_analytic:.6}"
    );

    // Greenhouse: 5 % stated tolerance.
    let rel_greenhouse = (inductance - greenhouse).abs() / greenhouse;
    println!("vs Greenhouse: rel {rel_greenhouse:.4} (tol 0.05)");
    assert!(rel_greenhouse < 0.05, "Greenhouse deviation {rel_greenhouse}");

    match pypeec_reference() {
        Some(path) => {
            let text = std::fs::read_to_string(&path).unwrap();
            let reference: serde_json::Value = serde_json::from_str(&text).unwrap();
            let pypeec_l = reference["l_h"].as_f64().expect("l_h in reference");
            let pypeec_r = reference["r_ohm"].as_f64().expect("r_ohm in reference");
            let version = reference["pypeec_version"].as_str().unwrap_or("?");
            println!(
                "pypeec {version}: L = {:.6} nH, R = {:.6} ohm ({} voxels)",
                pypeec_l * 1e9,
                pypeec_r,
                reference["conductor_voxels"].as_u64().unwrap_or(0),
            );
            let rel_pypeec = (inductance - pypeec_l).abs() / pypeec_l;
            println!("vs PyPEEC: rel {rel_pypeec:.4} (tol 0.02)");
            assert!(rel_pypeec < 0.02, "PyPEEC deviation {rel_pypeec}");
            // R: the voxel model's corners and terminal pads put it a few
            // per cent off the analytic bar sum; a wide band catches unit
            // errors without encoding voxelization detail.
            let rel_r = (resistance - pypeec_r).abs() / pypeec_r;
            println!("vs PyPEEC R: rel {rel_r:.4} (sanity band 0.25)");
            assert!(rel_r < 0.25, "PyPEEC R deviation {rel_r}");
        }
        None => {
            eprintln!(
                "SKIPPED (pypeec reference absent): regenerate with\n  \
                 python3 tools/pypeec_reference.py --out tools/pypeec_reference.json"
            );
        }
    }

    // The production result must carry the full provenance chain.
    assert_eq!(result.ports.len(), 1);
    assert_eq!(result.provenance.counts.ports, 1);
}